services:
#  IF YOU WANT TO RUN THE CODE IN THE IDE, COMMENT ALL THE APP CONFIGURATION
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/recipes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:14.17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=recipes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d recipes"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
